name: Python Test Suite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Replace with your Python version (e.g., 3.9)
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file
        # Alternatively, if using setup.py:
        # pip install .
    
    - name: Run tests with pytest
      run: |
        python -m pytest tests/ -v  # Adjust path to your tests if needed
        # If you use unittest instead:
        # python -m unittest discover